- name: copy file preloaded-vars.conf
  template: src=preload.j2 dest=/root/ossec-hids-3.6.0/etc/preloaded-vars.conf mode=0644

- name: install ossec
  shell: /root/ossec-hids-3.6.0/install.sh

- name: ossec config
  template: src=config.j2 dest=/var/ossec/etc/ossec.conf mode=0640
