- name: file authd.pass
  template: src=authd_pass.j2 dest=/var/ossec/etc/authd.pass mode=0644

- name: register to server
  shell: "/var/ossec/bin/agent-auth -m {{ server_ip }} -A {{ inventory_hostname }} -P /var/ossec/etc/authd.pass -d -d -d -d"

- name: restart ossec
  shell: /var/ossec/bin/ossec-control restart
